SELECT USER
FROM DUAL;
--==>> SCOTT

-- ○ 실습 테이블 생성
CREATE TABLE TBL_SCORE
( SID   NUMBER
, NAME  VARCHAR2(30)
, KOR   NUMBER(3)
, ENG   NUMBER(3)
, MAT   NUMBER(3)
);

--○ 제약조건 추가
ALTER TABLE TBL_SCORE
ADD CONSTRAINT SCORE_SID_PK PRIMARY KEY(SID);

ALTER TABLE TBL_SCORE
ADD (  CONSTRAINT SCORE_KOR_CK CHECK (KOR BETWEEN 0 AND 100)
     , CONSTRAINT SCORE_ENG_CK CHECK (ENG BETWEEN 0 AND 100)
     , CONSTRAINT SCORE_MAT_CK CHECK (MAT BETWEEN 0 AND 100));
     
-- ○ 시퀀스 생성     
CREATE SEQUENCE SCORESEQ
NOCACHE;

INSERT INTO TBL_SCORE(SID, NAME, KOR, ENG, MAT) VALUES ()

SELECT COUNT(*) AS COUNT FROM TBL_SCORE
;

SELECT SID, NAME, KOR, ENG, MAT, (KOR+ENG+MAT) "TOT", round((KOR+ENG+MAT)/3,2) "AVG"
FROM TBL_SCORE
ORDER BY SID;

select *
from tbl_score;

commit;

drop SEQUENCE SCORESEQ;






